name: Python package

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"] # Add more versions as needed
        os: [ubuntu-latest, windows-latest, macos-latest] # remove or add OSes as needed
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv and nox
        run: |
          python -m pip install --upgrade pip
          pip install uv nox

      - name: Run chores (Windows)
        if: runner.os == 'Windows'
        run: |
          chcp 65001
          nox -s chores
        env:
          PYTHONENCODING: utf-8

      - name: Run chores (non-Windows)
        if: runner.os != 'Windows'
        run: |
          nox -s chores

      - name: Run tests
        run: |
          nox -s tests